version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=notification_queue
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672" 
      - "15673:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: