version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=ff08c538111579e6c1408a01fae062b4474b2f35affc64dcc3c2f3f58ef03de9
      - TOKEN_HEADER_KEY=auth-token
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:8081
      - USER_SERVICE_URL=http://user-service:8082
      - QA_SERVICE_URL=http://qa-service:8083
      - VOTE_SERVICE_URL=http://vote-service:8084
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

